#### Numpy(넘파이) 특징
- 과학 계산을 위한 라이브러리(모듈)
- 행렬/배열 처리 및 연산

In [3]:
import numpy as np

tmp=[1,2,3,4,5,6]
arr=np.array(tmp)
print(tmp, "\n", arr)
print(type(tmp))
print(type(arr))

[1, 2, 3, 4, 5, 6] 
 [1 2 3 4 5 6]
<class 'list'>
<class 'numpy.ndarray'>


In [7]:
# ndarray => 동일 데이터만 사용 가능
tmp=[1, 2, 3, '사', 5, 6]
arr=np.array(tmp)
print(tmp, "\n", arr)

[1, 2, 3, '사', 5, 6] 
 ['1' '2' '3' '사' '5' '6']


- 배열의 차원

In [10]:
# 배열의 차원 확인
print(arr.ndim) # -> 1차원 배열을 갖고있다. # 1자 열로 구성되어 있다.
print(arr.shape) # 행과 열로 구성되어 있다.

1
(6,)


In [16]:
# 2차원 배열 생성
tmp=[[1,2,3],[4,5,6]]

arr=np.array(tmp) # 리스트를 2차원 배열로 변경
print(arr.shape)
print(arr)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [38]:
# 행/열 변환(차원 변환)
print(arr.reshape(6,)) # == arr.reshape(1,6)
print(arr.reshape(6,1))

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [44]:
tmp=[[[255, 255, 255], [200,235,200],[156, 232, 100]],
     [[100, 255, 100], [200,235,100],[56, 232, 100]],
     [[255, 100, 255], [100,235,100],[56, 100, 100]]]
# -> 3차원은ㅜ ㅜㅜㅜ 행, 열, 면

arr=np.array(tmp)
print(arr)
print(arr.shape)

[[[255 255 255]
  [200 235 200]
  [156 232 100]]

 [[100 255 100]
  [200 235 100]
  [ 56 232 100]]

 [[255 100 255]
  [100 235 100]
  [ 56 100 100]]]
(3, 3, 3)


In [56]:
# 차원 변경(1열로 변경): -1 자동으로 행/열 값을 설정
arr.reshape(-1, 1) # 결과 shape: (27, 1)
arr.reshape(1,-1) # shape: (1, 27)
arr.reshape(-1,) # shape: (27, ) -> 면이 사라진다.

array([255, 255, 255, 200, 235, 200, 156, 232, 100, 100, 255, 100, 200,
       235, 100,  56, 232, 100, 255, 100, 255, 100, 235, 100,  56, 100,
       100])

In [59]:
arr.reshape(2, -1) 

ValueError: ignored

In [60]:
arr.reshape(3, -1)

array([[255, 255, 255, 200, 235, 200, 156, 232, 100],
       [100, 255, 100, 200, 235, 100,  56, 232, 100],
       [255, 100, 255, 100, 235, 100,  56, 100, 100]])

- 넘파이 생성 및 자료형

In [64]:
print(np.arange(10))
print(np.arange(10).shape)
print(np.arange(5,10))
print(np.arange(1,10,2))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[5 6 7 8 9]
[1 3 5 7 9]


In [67]:
# np.zeros((3, 3)): 전체 데이터를 0으로 채워서 생성
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
# np.ones((3,3)): 3x3 배열을 1로 채워 생성
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

- 배열 인덱스(출력)

In [109]:
tmp=np.arange(9).reshape(3,-1)
tmp[0,0:] # output: array([0, 1, 2])
print(tmp)

print("1열 전체 출력",tmp[0:, 0])
print("1열 전체 출력",tmp[0:3, 0])
print("4,5,7,8 출력\n",tmp[1:3, 1:3])

print("1,6,8 출력\n",tmp[0,1],tmp[2,0],tmp[2,2])
print("차원 값을 이용한 출력\n",tmp[[0, 1], [0, 2]]) # -> [0,0]과 [1,2]로 해서 0과 5가 출력된다.

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1열 전체 출력 [0 3 6]
1열 전체 출력 [0 3 6]
4,5,7,8 출력
 [[4 5]
 [7 8]]
1,6,8 출력
 1 6 8
차원 값을 이용한 출력
 [0 5]


- 부울린 인덱스

In [120]:
# 2 x 3 의 배열 생성
tmp=np.arange(6).reshape(2, 3)
print(tmp)

bool_arr=np.array([[False, True, False],
                   [True, False, True]])
print(bool_arr)
print(tmp[bool_arr])

[[0 1 2]
 [3 4 5]]
[[False  True False]
 [ True False  True]]
[1 3 5]


##### [미션]
1. 1 ~ 9 숫자를 이용해 3 x 3 배열 생성
2. 데이터들 중 짝수인 값만 출력

In [121]:
print(tmp[tmp%2==0])

[0 2 4]


In [122]:
tmp=np.arange(1,10).reshape(3,3)
tmp

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
# 홀수 값 찾기!

bool_arr=np.array(tmp%2!=0)
print(tmp[bool_arr])

[1 3 5 7 9]
